import { BodyCondition } from '../types';

export const BODY_CONDITION_PRESETS: BodyCondition[] = [
  // ==========================================
  // 1. GESCHLECHTSWECHSEL / GENDER MORPHS
  // ==========================================
  {
    id: 'cond-gender-female',
    name: 'Feminisierung (Weibliche Metamorphose)',
    type: 'gender_change',
    category: 'Geschlechtswechsel',
    icon: '⚧️',
    isActive: false,
    severity: 'vollständig',
    source: 'Verwandlungszauber / Elixier der Venus',
    duration: 'Aktiv solange gewählt',
    description: 'Der physische Körper transformiert vollständig in eine weibliche Gestalt: Zierlichere Statur, weichere Gesichtszüge, weibliche Rundungen, anpassbare Körbchengröße und sanftere Stimme.',
    overrideGender: 'Weiblich',
    cupSizeOverride: 'C',
    heightModifierCm: -8,
    weightModifierKg: -10,
    muscleMassModifier: -6,
    bodyFatModifier: +8,
    statusTag: '⚧️ Weibliche Form',
    specialFeatures: ['Weibliche Körperform & Rundungen', 'Sanfte Gesichtszüge', 'Höhere Stimmlage']
  },
  {
    id: 'cond-gender-male',
    name: 'Maskulinisierung (Männliche Metamorphose)',
    type: 'gender_change',
    category: 'Geschlechtswechsel',
    icon: '♂️',
    isActive: false,
    severity: 'vollständig',
    source: 'Kriegstrank / Mars-Metamorphose',
    duration: 'Aktiv solange gewählt',
    description: 'Der Körper transformiert in eine athletisch-maskuline Gestalt: Breitere Schultern, Zunahme an Muskelmasse, markante Kinnpartie und tiefere Resonanz der Stimme.',
    overrideGender: 'Männlich',
    cupSizeOverride: '-',
    heightModifierCm: +8,
    weightModifierKg: +12,
    muscleMassModifier: +10,
    bodyFatModifier: -6,
    statusTag: '♂️ Männliche Form',
    specialFeatures: ['Breite Schultern & V-Form', 'Markante Kieferpartie', 'Tiefe sonore Stimme']
  },
  {
    id: 'cond-gender-androgynous',
    name: 'Androgyne Astral-Metamorphose',
    type: 'gender_change',
    category: 'Geschlechtswechsel',
    icon: '✨',
    isActive: false,
    severity: 'vollständig',
    source: 'Sternenstaub-Ritual',
    duration: 'Permanent',
    description: 'Der Körper nimmt eine vollkommen ebenmäßige, geschlechtsneutrale und ätherische Gestalt an. Schimmernde Haut, elegante Züge und vollkommene Harmonie.',
    overrideGender: 'Androgyn',
    cupSizeOverride: 'AA',
    heightModifierCm: +2,
    weightModifierKg: -4,
    skinToneOverride: 'Mondscheinschimmernd',
    statusTag: '✨ Astralgestalt',
    specialFeatures: ['Ebenmäßige androgyne Gesichtszüge', 'Grazil-ätherische Haltung']
  },

  // ==========================================
  // 2. RASSENWECHSEL & METAMORPHOSEN
  // ==========================================
  {
    id: 'cond-race-lightelf',
    name: 'Lichtelfen-Metamorphose',
    type: 'race_change',
    category: 'Rassenwechsel',
    icon: '🧝',
    isActive: false,
    severity: 'vollständig',
    source: 'Uralter Weltenbaum-Segen',
    duration: 'Dauerhafte Rassenanpassung',
    description: 'Verwandlung in einen edlen Lichtelfen: Elegante, lange Elfenohren, kristallklare smaragdgrüne Augen, silbernes Seidenhaar und feine silbrige Haut.',
    overrideRace: 'Lichtelf',
    overrideRaceFeatures: 'Lange spitze Elfenohren, silberweiße Aura, übernatürlich feines Gehör',
    heightModifierCm: +6,
    weightModifierKg: -5,
    hairColorOverride: 'Silberweiß glänzend',
    eyeColorOverride: 'Smaragdgrün leuchtend',
    skinToneOverride: 'Makellos Alabaster',
    statusTag: '🧝 Lichtelf',
    healingFactorModifier: 1,
    statBuffs: { mpBonus: 30, staminaBonus: 10 },
    specialFeatures: ['Spitze Elfenohren', 'Silberne Haarsträhnen', 'Feinstrukturierte Aura']
  },
  {
    id: 'cond-race-demon',
    name: 'Dämonische Metamorphose (Abyssal-Lord)',
    type: 'race_change',
    category: 'Rassenwechsel',
    icon: '😈',
    isActive: false,
    severity: 'stark',
    source: 'Höllenpakt / Dunkle Netherflamme',
    duration: 'Aktiv',
    description: 'Der Körper mutiert in eine dämonische Hoheitsgestalt: Gebogene Obsidianhörner sprießen aus der Stirn, fledermausartige Schwingen entfalten sich und die Augen glühen in brennendem Karminrot.',
    overrideRace: 'Dämon',
    overrideRaceFeatures: 'Gebogene Dämonenhörner, ledrige Schwingen, spitze Fangzähne, feurige Augen',
    hornsOverride: true,
    wingsOverride: true,
    heightModifierCm: +12,
    weightModifierKg: +15,
    muscleMassModifier: +14,
    eyeColorOverride: 'Karminrot glühend',
    statusTag: '😈 Dämonengestalt',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 40, mpBonus: 20 },
    specialFeatures: ['Obsidian-Dämonenhörner', 'Dunkle Schwingen', 'Glühende rote Augen', 'Raubtier-Reißzähne']
  },
  {
    id: 'cond-race-dragonborn',
    name: 'Drachenblut-Transformation (Drachenmensch)',
    type: 'race_change',
    category: 'Rassenwechsel',
    icon: '🐉',
    isActive: false,
    severity: 'stark',
    source: 'Drachenherz-Transfusion',
    duration: 'Aktiv',
    description: 'Drachenhafte Züge brechen hervor: Schimmernde Drachenschuppen an Wangen und Unterarmen, schlitzförmige Reptilienpupillen, mächtige Drachenflügel und unzerstörbare Muskelhärte.',
    overrideRace: 'Drachenmensch',
    overrideRaceFeatures: 'Drachenschuppen an Schläfen & Gliedmaßen, reptilische Schlitzaugen, Drachenschwingen',
    wingsOverride: true,
    hornsOverride: true,
    heightModifierCm: +15,
    weightModifierKg: +20,
    muscleMassModifier: +18,
    eyeColorOverride: 'Goldgelbe Reptilienpupillen',
    skinToneOverride: 'Leicht schuppig bronzen',
    statusTag: '🐉 Drachenblut',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 50, staminaBonus: 25 },
    specialFeatures: ['Drachenschuppen-Muster', 'Drachenschwingen', 'Geschlitzte Goldaugen', 'Gepanzerte Knochenstruktur']
  },
  {
    id: 'cond-race-kitsune',
    name: 'Kitsune-Verwandlung (Neunschwänzige Fuchswandlerin)',
    type: 'race_change',
    category: 'Rassenwechsel',
    icon: '🦊',
    isActive: false,
    severity: 'mittel',
    source: 'Geistfüchsin-Ritual',
    duration: 'Aktiv',
    description: 'Fuchsartige Eleganz: Weiche, bewegliche Fuchsohren auf dem Kopf, ein bis mehrere buschige Fuchsschweife mit weißen Spitzen und geschärfte goldene Augen.',
    overrideRace: 'Kitsune / Tiermensch',
    overrideRaceFeatures: 'Flauschige Fuchsohren, Fuchsschweif(e), geschärfter Geruchssinn, Fuchsfeuer-Aura',
    heightModifierCm: 0,
    weightModifierKg: +2,
    eyeColorOverride: 'Bernsteingold',
    statusTag: '🦊 Kitsune',
    statBuffs: { mpBonus: 35, staminaBonus: 15 },
    specialFeatures: ['Flauschige Fuchsohren', 'Fuchsschweif mit weißer Spitze', 'Geschärfte Sinne', 'Fuchsfeuer-Funken']
  },
  {
    id: 'cond-race-vampire',
    name: 'Vampirische Nocturne-Gestalt',
    type: 'race_change',
    category: 'Rassenwechsel',
    icon: '🦇',
    isActive: false,
    severity: 'vollständig',
    source: 'Der Ursprüngliche Blutkuss',
    duration: 'Ewig',
    description: 'Die Gestalt der Nacht: Porzellanblasse Haut, rubinrote Raubtieraugen, verlängerte spitze Eckzähne und eine unheimliche, hypnotische Anziehungskraft.',
    overrideRace: 'Vampir',
    overrideRaceFeatures: 'Scharfe Reißzähne, porzellanweiße Haut, rubinrote Augen, übermenschliche Schnelligkeit',
    skinToneOverride: 'Porzellanblass marmoriert',
    eyeColorOverride: 'Rubinrot blutdürstig',
    statusTag: '🦇 Vampirfürst',
    healingFactorModifier: 3,
    statBuffs: { hpBonus: 30, mpBonus: 40, staminaBonus: 20 },
    specialFeatures: ['Scharfe Reißzähne', 'Hypnotische Blutaugen', 'Schattenschleier', 'Kühle Körpertemperatur']
  },
  {
    id: 'cond-race-titan',
    name: 'Titanen-Gestalt (Kolossaler Halbgott)',
    type: 'race_change',
    category: 'Rassenwechsel',
    icon: '🗿',
    isActive: false,
    severity: 'stark',
    source: 'Essenz der Ur-Titanen',
    duration: 'Aktiv',
    description: 'Monumentales Wachstum: Die Körpergröße wächst drastisch um +45 cm an, titanische Muskelmasse und erderschütternde Physis.',
    overrideRace: 'Titan / Koloss',
    overrideRaceFeatures: 'Gigantische Statur, titanische Knochendichte, rissige Steinhaut-Nuancen',
    heightModifierCm: +45,
    weightModifierKg: +55,
    muscleMassModifier: +25,
    bodyFatModifier: -4,
    statusTag: '🗿 Titanengestalt',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 80, staminaBonus: 40 },
    specialFeatures: ['Übermenschliche Körperhöhe (+45cm)', 'Massive Muskelberge', 'Felsenharte Hautstruktur']
  },

  // ==========================================
  // 3. FLÜCHE & HEXEREIEN (CURSES & HEXES)
  // ==========================================
  {
    id: 'cond-curse-shrink',
    name: 'Schrumpffluch (Chibi / Feengröße)',
    type: 'curse',
    category: 'Fluch',
    icon: '🧚',
    isActive: false,
    severity: 'stark',
    source: 'Boshafte Hexe des Zauberwalds',
    duration: 'Bis Gegenzauber gewirkt wird',
    description: 'Der gesamte Körper schrumpft drastisch auf Miniaturgröße (ca. 35-45 cm)! Waffen und Ausrüstung wirken riesig, die Stimme wird zart und piepsig, während die Beweglichkeit hoch bleibt.',
    heightModifierCm: -130,
    weightModifierKg: -55,
    cupSizeOverride: 'AA',
    muscleMassModifier: -10,
    statusTag: '🧚 Schrumpffluch (Chibi)',
    specialFeatures: ['Miniaturkörper (Feengröße)', 'Piepsige hohe Stimme', 'Geringe Tragkraft']
  },
  {
    id: 'cond-curse-petrify',
    name: 'Versteinerungsfluch (Gorgonenblick)',
    type: 'curse',
    category: 'Fluch',
    icon: '🗿',
    isActive: false,
    severity: 'mittel',
    source: 'Blick einer uralten Gorgone',
    duration: 'Schreitet stündlich voran',
    description: 'Die Haut verhärtet sich zu grauem, rauem Granit. Gelenke werden steif, Gewicht verdoppelt sich, physische Abwehr steigt drastisch, aber Geschwindigkeit sinkt drastisch.',
    skinToneOverride: 'Rauer grauer Granit / Marmor',
    eyeColorOverride: 'Steinern trüb',
    weightModifierKg: +40,
    muscleMassModifier: +5,
    statusTag: '🗿 Versteinert',
    specialFeatures: ['Granithaut-Struktur', 'Schwere steinige Glieder', 'Immunität gegen Schnitte']
  },
  {
    id: 'cond-curse-shadow-rot',
    name: 'Schattenbrand & Verderbnis-Mal',
    type: 'curse',
    category: 'Fluch',
    icon: '☠️',
    isActive: false,
    severity: 'mittel',
    source: 'Kult des Vergessenen Schattenfürsten',
    duration: 'Permanent bis Erlösung',
    description: 'Pechschwarze, pulsierende Adern kriechen vom Hals über Brust und Arme. Bei Magieeinsatz brennen die Runen violett auf und verströmen dunklen Nebel.',
    skinToneOverride: 'Blass mit schwarzen pulsierenden Adern',
    eyeColorOverride: 'Pechschwarz mit violettem Schein',
    statusTag: '☠️ Schattenbrand',
    statBuffs: { mpBonus: 20, hpBonus: -15 },
    specialFeatures: ['Pulsierende Schattenadern am Hals & Brust', 'Violettes Glimmen', 'Kalter Pesthauch']
  },
  {
    id: 'cond-curse-beast',
    name: 'Lykanthropie (Werwolf-Bestienfluch)',
    type: 'curse',
    category: 'Fluch',
    icon: '🐺',
    isActive: false,
    severity: 'stark',
    source: 'Biss eines Alphawolfs im Vollmond',
    duration: 'Erwacht bei Nacht / Kampf',
    description: 'Raubtierhafte Verwandlung: Scharfe Reißzähne, spitze Wolfsohren, dichte Fellansätze an den Unterarmen, messerscharfe Krallen und glühende Raubtieraugen.',
    overrideRaceFeatures: 'Wolfsohren, Reißzähne, messerscharfe Krallen, verstärkter Nacken',
    heightModifierCm: +10,
    weightModifierKg: +18,
    muscleMassModifier: +20,
    eyeColorOverride: 'Grelles Bernstein-Raubtierauge',
    statusTag: '🐺 Bestienfluch',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 40, staminaBonus: 30 },
    specialFeatures: ['Messerscharfe Krallen an Händen', 'Raubtier-Fangzähne', 'Wolfsohren', 'Fellstreifen an Rücken & Armen']
  },
  {
    id: 'cond-curse-aging',
    name: 'Altersfluch (Temporäre Vergreisung)',
    type: 'curse',
    category: 'Fluch',
    icon: '⏳',
    isActive: false,
    severity: 'stark',
    source: 'Sanduhr der Zeit-Chronomagier',
    duration: '3 Tage',
    description: 'Der Körper altert schlagartig um mehrere Jahrzehnte: Schneeweißes Haar, Falten, schwindende Muskelmasse, jedoch gesteigerte Weisheit und Magiekontrolle.',
    hairColorOverride: 'Schneeweiß / Silbergrau',
    muscleMassModifier: -15,
    bodyFatModifier: -5,
    statusTag: '⏳ Altersfluch (Gealtert)',
    statBuffs: { mpBonus: 50, hpBonus: -20, staminaBonus: -25 },
    specialFeatures: ['Schneeweißes greises Haar', 'Altersfalten an Gesicht & Händen', 'Zittrige Hände bei Anstrengung']
  },
  {
    id: 'cond-curse-gluttony',
    name: 'Fluch der Völlerei (Aufblähung & Gewichtszunahme)',
    type: 'curse',
    category: 'Fluch',
    icon: '🍖',
    isActive: false,
    severity: 'mittel',
    source: 'Fluch der Fressdämonin',
    duration: 'Bis Fastenritual',
    description: 'Der Körper speichert massiv Fett und Rundungen an: Deutliche Zunahme an Körperfett (+18%), weicher runder Bauch, volle Wangen und stark vergrößerte Proportionen.',
    weightModifierKg: +28,
    bodyFatModifier: +18,
    cupSizeOverride: 'F',
    muscleMassModifier: -4,
    statusTag: '🍖 Völlerei-Fluch',
    specialFeatures: ['Weiche runde Körperfülle', 'Deutliche Taillenverbreiterung', 'Schwerfälligere Bewegungen']
  },

  // ==========================================
  // 4. SEGEN & GÖTTLICHE GABEN (BLESSINGS)
  // ==========================================
  {
    id: 'cond-blessing-angel',
    name: 'Segen der Himmelsgöttin (Engelsflügel & Heiligenschein)',
    type: 'blessing',
    category: 'Segen',
    icon: '🪽',
    isActive: false,
    severity: 'vollständig',
    source: 'Erzengel Michael & Göttin des Lichts',
    duration: 'Göttliche Gnade',
    description: 'Strahlende himmlische Verwandlung: Ein Paar schneeweißer, majestätischer Engelsflügel entfaltet sich auf dem Rücken, ein sanft leuchtender Heiligenschein schwebt über dem Haupt und makellose Reinheit erfüllt den Körper.',
    wingsOverride: true,
    skinToneOverride: 'Strahlend makellos mit goldenem Schimmer',
    eyeColorOverride: 'Göttlich Gold leuchtend',
    hairColorOverride: 'Platinblond mit Lichtreflexen',
    statusTag: '🪽 Engelssegen',
    healingFactorModifier: 3,
    statBuffs: { hpBonus: 40, mpBonus: 60, staminaBonus: 30 },
    specialFeatures: ['Majestätische weiße Engelsflügel', 'Schwebender goldener Heiligenschein', 'Sanfte Licht-Aura', 'Wunderschöne Ausstrahlung']
  },
  {
    id: 'cond-blessing-invulnerable',
    name: 'Segen der Unverwundbarkeit (Kristallene Titanenhaut)',
    type: 'blessing',
    category: 'Segen',
    icon: '🛡️',
    isActive: false,
    severity: 'stark',
    source: 'Uralter Erd- und Schutzgott',
    duration: 'Dauerhaft',
    description: 'Die Haut überzieht sich mit einem unzerstörbaren, kristallinen Schutzschleier. Klingen und Projektile prallen mit lautem Klirren ab, während die Muskulatur stahlhart wird.',
    skinToneOverride: 'Kristalliner Diamantschimmer',
    muscleMassModifier: +15,
    statusTag: '🛡️ Kristallpanzer',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 100, staminaBonus: 20 },
    specialFeatures: ['Diamantene Kristallschicht auf Haut', 'Kugelsichere Knochen', 'Erhöhter Rüstungswert']
  },
  {
    id: 'cond-blessing-fire',
    name: 'Flammen-Segnung (Phönix-Aura & Gluthaar)',
    type: 'blessing',
    category: 'Segen',
    icon: '🔥',
    isActive: false,
    severity: 'mittel',
    source: 'Göttlicher Ur-Phönix',
    duration: 'Ewig',
    description: 'Das Feuer der Wiedergeburt: Die Haarspitzen lodern in echten roten Flammen, die Augen glühen wie heiße Kohlen und der Körper verströmt wohlige, magische Wärme.',
    hairColorOverride: 'Flammenrot mit lodernden Spitzen',
    eyeColorOverride: 'Glutrot mit goldenem Kern',
    statusTag: '🔥 Phönix-Segen',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 25, mpBonus: 45 },
    specialFeatures: ['Lodernde feurige Haarspitzen', 'Glutrote Augen', 'Hitzeschild um den Körper', 'Wiedergeburtsfunken']
  },
  {
    id: 'cond-blessing-frost',
    name: 'Frostkristall-Segen (Eisgöttin-Anmut)',
    type: 'blessing',
    category: 'Segen',
    icon: '❄️',
    isActive: false,
    severity: 'mittel',
    source: 'Schnee- und Frostkönigin',
    duration: 'Ewig',
    description: 'Die Eleganz des ewigen Eises: Schneeweißes Haar mit Eiskristallen, eisblaue, kristallklare Augen, erfrischende Aura und Kälteresistenz.',
    hairColorOverride: 'Schneeweiß mit Eiskristall-Glanz',
    eyeColorOverride: 'Eisblau kristallklar',
    skinToneOverride: 'Kühles Alabasterweiß',
    statusTag: '❄️ Eissegen',
    healingFactorModifier: 1,
    statBuffs: { mpBonus: 50, staminaBonus: 15 },
    specialFeatures: ['Eiskristall-Ornamente im Haar', 'Kühler Atem', 'Eisblaue Augen', 'Kälteresistente Haut']
  },
  {
    id: 'cond-blessing-vitality',
    name: 'Segen der Fruchtbarkeit & Vitalität (Aphrodite-Segen)',
    type: 'blessing',
    category: 'Segen',
    icon: '🌸',
    isActive: false,
    severity: 'mittel',
    source: 'Göttin der Liebe und Fruchtbarkeit',
    duration: 'Dauerhaft',
    description: 'Blühende Anmut: Rosiger gesunder Teint, geschmeidige Haut, verstärkte weibliche Reize, unerschöpfliche Vitalität und aphrodisierende Aura.',
    cupSizeOverride: 'E',
    bodyFatModifier: +4,
    skinToneOverride: 'Rosig frisch & samtweich',
    statusTag: '🌸 Göttliche Vitalität',
    healingFactorModifier: 2,
    statBuffs: { hpBonus: 35, staminaBonus: 35 },
    specialFeatures: ['Samtweiche rosige Haut', 'Aphrodisierender Duft', 'Gesteigerte Fruchtbarkeit & Ausdauer']
  }
];
