// -*- coding: utf-8 -*-
/**
 * Detaillierter Katalog aller Berufe und ihrer benötigten Gegenstände:
 * - Rohstoffe (Mining, Holz, Landwirtschaft, Jagd, etc.)
 * - Materialien & Zwischenprodukte (Barren, Bretter, Leder, Stoffe, Halbzeuge)
 * - Werkzeuge & Arbeitsgeräte
 * - Berufsbekleidung & Schutzausrüstung
 * - Typische Erzeugnisse & Endprodukte
 *
 * Alle Bezeichnungen sind rein grammatikalisch singulär, eindeutig und granular
 * (keine Doppel-/Mischbezeichnungen) und für das Wirtschafts- & Managementsystem optimiert.
 */

import { StandardItemDefinition } from './standardItemsData';

export const PROFESSION_ITEMS_CATALOG: StandardItemDefinition[] = [
  // =========================================================================
  // 1. SCHMIED & WAFFENSCHMIED (Blacksmith / Weaponsmith / Armorsmith)
  // =========================================================================
  {
    id: 'prof-smith-raw-iron',
    title: 'Eisenerz',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Metallerze',
    unit: 'kg',
    pricePerUnit: 3,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schweres, rotbraunes Rohgestein mit dichten Eisenadern. Grundstoff für Rennöfen und Esse.',
    details: { baseRawMaterial: 'Eisenerz', requiredProfession: 'Schmied', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-smith-mat-iron-ingot',
    title: 'Eisenbarren',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Barren & Metallhalbzeuge',
    unit: 'Stück',
    pricePerUnit: 10,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Gegossener und ausgeschmiedeter Barren aus raffiniertem Schmiedeeisen.',
    details: { baseRawMaterial: 'Eisen', requiredProfession: 'Schmied', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-smith-mat-steel-ingot',
    title: 'Stahlbarren',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Barren & Metallhalbzeuge',
    unit: 'Stück',
    pricePerUnit: 25,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Hochwertiger, kohlenstoffgehärteter Federstahl für scharfe Klingen und Rüstungsplatten.',
    details: { baseRawMaterial: 'Stahl', requiredProfession: 'Schmied', useDomains: ['wirtschaft', 'handwerk', 'armee'] }
  },
  {
    id: 'prof-smith-mat-rivets',
    title: 'Eisennieten',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Platten, Nägel & Beschläge',
    unit: 'Beutel',
    pricePerUnit: 4,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Kleine, zähe Schmiedenieten zum Verbinden von Rüstungsplatten und Lederriemen.',
    details: { requiredProfession: 'Schmied', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-smith-tool-hammer',
    title: 'Schmiedehammer',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schmiedewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Balancierter Handfäustel mit gehärteter Finne zum Formen von glühendem Metall auf dem Amboss.',
    details: { toolType: 'Schmiedehammer', requiredProfession: 'Schmied', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-smith-tool-tongs',
    title: 'Schmiedezange',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schmiedewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Lange Flachbackenzange aus gehärtetem Eisen zum sicheren Greifen glühender Werkstücke.',
    details: { toolType: 'Schmiedezange', requiredProfession: 'Schmied', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-smith-tool-anvil',
    title: 'Schmiedeamboss',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schmiedewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 150,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Massiver, hundert Kilo schwerer Stahlamboss mit Rund- und Flachhorn auf massivem Eichenklotz.',
    details: { toolType: 'Amboss', requiredProfession: 'Schmied', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-smith-tool-bellows',
    title: 'Blasebalg',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schmiedewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 35,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Großer Lederblasebalg mit Eisenrohr zum Anfachen der Esse auf Weißglut.',
    details: { toolType: 'Blasebalg', requiredProfession: 'Schmied', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-smith-cloth-apron',
    title: 'Schmiedeschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 22,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schwere Schürze aus dickem Rindsleder zum Schutz vor Funkenflug und Metallspritzern.',
    details: { clothingSlot: 'body', requiredProfession: 'Schmied', useDomains: ['handwerk', 'alltag'] }
  },
  {
    id: 'prof-smith-cloth-gloves',
    title: 'Schmiedehandschuhe',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Paar',
    pricePerUnit: 12,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Hitzebeständige Lederhandschuhe mit langen Stulpen zum Schutz von Händen und Unterarmen.',
    details: { clothingSlot: 'hands', requiredProfession: 'Schmied', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-smith-prod-horseshoe',
    title: 'Hufeisen',
    builderType: 'Material',
    mainCategory: 'Produkte',
    subCategory: 'Handwerksprodukte',
    unit: 'Stück',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Geschmiedetes Hufeisen mit Rillen und Nagellöchern zum Beschlagen von Reit- und Zugtieren.',
    details: { producingHoldingName: 'Schmiede', requiredProfession: 'Schmied', useDomains: ['wirtschaft', 'alltag'] }
  },

  // =========================================================================
  // 2. BERGMANN & MINENARBEITER (Miner)
  // =========================================================================
  {
    id: 'prof-miner-tool-pickaxe',
    title: 'Spitzhacke',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Bergbau & Steinbruch',
    unit: 'Stück',
    pricePerUnit: 15,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schwere Spitzhacke mit gehärteter Stahlspitze und Eschenstiel zum Schlagen von Fels und Erz.',
    details: { toolType: 'Spitzhacke', requiredProfession: 'Bergmann', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-miner-tool-chisel',
    title: 'Schlägel und Eisen',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Bergbau & Steinbruch',
    unit: 'Set',
    pricePerUnit: 16,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Traditionelles Bergmannswerkzeug bestehend aus Fäustel und Bergeisen zum präzisen Vortrieb.',
    details: { toolType: 'Meißelset', requiredProfession: 'Bergmann', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-miner-tool-lamp',
    title: 'Grubenlampe',
    builderType: 'Alltagsgegenstand',
    mainCategory: 'Alltags- & Haushaltsgegenstände',
    subCategory: 'Beleuchtung (Lampen, Kerzen, Laternen)',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Messing-Öllampe mit Schutzgitter und Aufhängung zum gefahrlosen Ausleuchten von Bergstollen.',
    details: { requiredProfession: 'Bergmann', useDomains: ['wirtschaft', 'abenteuer'] }
  },
  {
    id: 'prof-miner-cloth-helmet',
    title: 'Grubenhelm',
    builderType: 'Rüstung',
    mainCategory: 'Rüstung & Schutzausrüstung',
    subCategory: 'Helme & Kopfschutz',
    unit: 'Stück',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Verstärkte Lederkappe mit Metallplatten gegen herabfallende Steine und Geröll.',
    details: { clothingSlot: 'head', requiredProfession: 'Bergmann', useDomains: ['handwerk', 'abenteuer'] }
  },
  {
    id: 'prof-miner-cloth-boots',
    title: 'Grubenstiefel',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Schuhe, Stiefel & Schuhwerk',
    unit: 'Paar',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Wasserdichte Stiefel aus gefettetem Leder mit dicker Holzsohle gegen spitzen Schotter.',
    details: { clothingSlot: 'feet', requiredProfession: 'Bergmann', useDomains: ['handwerk'] }
  },

  // =========================================================================
  // 3. HOLZFÄLLER & FORSTWIRT (Lumberjack / Forester)
  // =========================================================================
  {
    id: 'prof-lumber-tool-felling-axe',
    title: 'Holzfälleraxt',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 22,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Breit geschliffene Axt mit geschwungenem Hickory-Stiel zum zügigen Fällen mächtiger Stämme.',
    details: { toolType: 'Axt', requiredProfession: 'Holzfäller', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-lumber-tool-two-man-saw',
    title: 'Trummsäge',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 30,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Zweimannsäge aus gehärtetem Bandstahl mit beidseitigen Holzgriffen zum Ablängen dicker Stämme.',
    details: { toolType: 'Säge', requiredProfession: 'Holzfäller', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-lumber-tool-wedge',
    title: 'Fällkeil',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 4,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Massiver Hartholz- oder Eisenkeil zum Führen der Fällrichtung und Sichern des Sägeschnitts.',
    details: { requiredProfession: 'Holzfäller', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-lumber-cloth-shirt',
    title: 'Holzfällerhemd',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 10,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dickes, wärmendes Wollhemd mit verstärkten Schultern für harte Waldarbeit bei Wind und Kälte.',
    details: { clothingSlot: 'torso', requiredProfession: 'Holzfäller', useDomains: ['alltag', 'handwerk'] }
  },
  {
    id: 'prof-lumber-cloth-boots',
    title: 'Schnittschutzstiefel',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Schuhe, Stiefel & Schuhwerk',
    unit: 'Paar',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Robuste Schaftstiefel aus derbem Rindsleder mit verstärkter Kappe.',
    details: { clothingSlot: 'feet', requiredProfession: 'Holzfäller', useDomains: ['handwerk'] }
  },

  // =========================================================================
  // 4. SCHREINER & ZIMMERMANN (Carpenter / Woodworker)
  // =========================================================================
  {
    id: 'prof-carp-mat-plank',
    title: 'Bretter',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Bretter & Bauholz',
    unit: 'Stück',
    pricePerUnit: 6,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Sauber gesägte, abgelagerte Holzbretter für Möbelbau, Wagenbau und Wandverkleidung.',
    details: { baseRawMaterial: 'Holz', requiredProfession: 'Schreiner', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-carp-mat-beam',
    title: 'Holzbalken',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Bretter & Bauholz',
    unit: 'Stück',
    pricePerUnit: 16,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Behauener Tragbalken aus Eichen- oder Kiefernholz für Dachstühle und Fachwerk.',
    details: { baseRawMaterial: 'Holz', requiredProfession: 'Zimmermann', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-carp-mat-glue',
    title: 'Holzleim',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Verarbeitete Materialien',
    unit: 'Tiegel',
    pricePerUnit: 5,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Ausgekochter Knochen- und Hautleim für feste Holzverbindungen in der Tischlerei.',
    details: { requiredProfession: 'Schreiner', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-carp-tool-plane',
    title: 'Holzhobel',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 16,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Hölzerner Schlichthobel mit justierbarem Stahlhobeleisen für glatte Holzoberflächen.',
    details: { toolType: 'Hobel', requiredProfession: 'Schreiner', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-carp-tool-chisels',
    title: 'Stechbeitelsatz',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Set',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Set geschliffener Stech- und Hohlbeitel in verschiedenen Breiten zum Einstemmen von Zapfen.',
    details: { toolType: 'Stechbeitel', requiredProfession: 'Schreiner', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-carp-tool-hand-saw',
    title: 'Handsäge',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Fein gezahnter Fuchsschwanz für präzise Schnitte bei Möbel- und Werkstattarbeiten.',
    details: { toolType: 'Säge', requiredProfession: 'Schreiner', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-carp-cloth-apron',
    title: 'Schreinerschnittschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 15,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Segeltuchschürze mit aufgenähten Fächern für Zollstock, Bleistift und Stechbeitel.',
    details: { clothingSlot: 'body', requiredProfession: 'Schreiner', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-carp-cloth-hat',
    title: 'Zimmermannshut',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Kopfbedeckungen & Hüte',
    unit: 'Stück',
    pricePerUnit: 12,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Breitkrempiger schwarzer Wollfilzhut für zünftige Zimmerleute auf der Walz.',
    details: { clothingSlot: 'head', requiredProfession: 'Zimmermann', useDomains: ['alltag', 'handwerk'] }
  },
  {
    id: 'prof-carp-prod-chest',
    title: 'Holztruhe',
    builderType: 'Alltagsgegenstand',
    mainCategory: 'Alltags- & Haushaltsgegenstände',
    subCategory: 'Behälter, Truhen & Gefäße',
    unit: 'Stück',
    pricePerUnit: 35,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Verzapfte Eichentruhe mit schmiedeeisernen Eckbeschlägen und Vorhängeschloss-Öse.',
    details: { producingHoldingName: 'Handwerkswerkstatt', requiredProfession: 'Schreiner', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 5. STEINMETZ & MAURER (Stonemason / Mason)
  // =========================================================================
  {
    id: 'prof-mason-raw-granite',
    title: 'Granit',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Steine, Erden & Ton',
    unit: 'kg',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Extrem harter, wetterbeständiger Tiefengesteinsblock für Fundamente und Befestigungen.',
    details: { baseRawMaterial: 'Granit', requiredProfession: 'Steinmetz', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-mason-mat-mortar',
    title: 'Mörtel',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Verarbeitete Materialien',
    unit: 'Sack',
    pricePerUnit: 4,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Mischung aus gelöschtem Kalk und Quarzsand zum Binden von Mauerwerk.',
    details: { requiredProfession: 'Maurer', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-mason-tool-mallet',
    title: 'Steinmetzhammer',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Steinbearbeitung & Maurerei',
    unit: 'Stück',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Ausgewuchteter Holz- oder Eisenfäustel zum Führen von Steinmetzmeißeln.',
    details: { toolType: 'Steinmetzhammer', requiredProfession: 'Steinmetz', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-mason-tool-chisels',
    title: 'Spitzmeißel',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Steinbearbeitung & Maurerei',
    unit: 'Stück',
    pricePerUnit: 12,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Gehärteter Meißel aus Schmiedestahl zum groben Behauen und Aushöhlen von Steinblöcken.',
    details: { toolType: 'Meißel', requiredProfession: 'Steinmetz', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-mason-tool-trowel',
    title: 'Maurerkelle',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Steinbearbeitung & Maurerei',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dreieckiges Stahlblatt mit gewinkeltem Holzheft zum Auftragen und Glätten von Mörtel.',
    details: { toolType: 'Maurerkelle', requiredProfession: 'Maurer', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-mason-cloth-apron',
    title: 'Lederschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Strapazierfähige Schürze aus festem Leder zum Schutz vor scharfkantigem Steinsplitterflug.',
    details: { clothingSlot: 'body', requiredProfession: 'Steinmetz', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-mason-prod-ashlar',
    title: 'Quaderstein',
    builderType: 'Material',
    mainCategory: 'Produkte',
    subCategory: 'Handwerksprodukte',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Maßhaltig behauener Werkstein aus Sandstein oder Kalkstein für Torbögen und Mauern.',
    details: { producingHoldingName: 'Mine', requiredProfession: 'Steinmetz', useDomains: ['wirtschaft', 'handwerk'] }
  },

  // =========================================================================
  // 6. BÄCKER & MÜLLER (Baker / Miller)
  // =========================================================================
  {
    id: 'prof-baker-raw-grain-wheat',
    title: 'Weizen',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Getreide & Feldfrüchte',
    unit: 'kg',
    pricePerUnit: 1,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Goldgelbe, gereinigte Weizenkörner aus der sommerlichen Ernte.',
    details: { baseRawMaterial: 'Weizen', requiredProfession: 'Müller', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-baker-mat-flour-wheat',
    title: 'Weizenmehl',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Verarbeitete Materialien',
    unit: 'kg',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Fein vermahlenes, gesiebtes weißes Mehl für helle Brote, Brötchen und Gebäck.',
    details: { baseRawMaterial: 'Weizen', requiredProfession: 'Bäcker', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-baker-mat-flour-rye',
    title: 'Roggenmehl',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Verarbeitete Materialien',
    unit: 'kg',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Kräftiges, dunkles Roggenmehl für herzhafte Bauernbrote und Sauerteigwaren.',
    details: { baseRawMaterial: 'Roggen', requiredProfession: 'Bäcker', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-baker-tool-peel',
    title: 'Backschieber',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Kochen & Küchenwerkzeuge',
    unit: 'Stück',
    pricePerUnit: 12,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Langstieliges Holzbrett zum Einschieben und Herausholen von Laiben aus dem heißen Steinofen.',
    details: { toolType: 'Backschieber', requiredProfession: 'Bäcker', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-baker-tool-trough',
    title: 'Knettrog',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Kochen & Küchenwerkzeuge',
    unit: 'Stück',
    pricePerUnit: 25,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Ausgehöhlter Holzbacktrog aus Ahornholz für das schwere Ansetzen und Kneten des Brotteigs.',
    details: { toolType: 'Knettrog', requiredProfession: 'Bäcker', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-baker-cloth-apron',
    title: 'Bäckerschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Weißes Leinentuch zum Binden, schützt vor Mehlstaub und Teigspritzern in der Backstube.',
    details: { clothingSlot: 'body', requiredProfession: 'Bäcker', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-baker-cloth-cap',
    title: 'Bäckermütze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Kopfbedeckungen & Hüte',
    unit: 'Stück',
    pricePerUnit: 4,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Leichte, weiße Stoffmütze für saubere Arbeitsbedingungen in Mühle und Backhaus.',
    details: { clothingSlot: 'head', requiredProfession: 'Bäcker', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-baker-prod-rye-bread',
    title: 'Roggenbrot',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Brot & Backwaren',
    unit: 'Laib',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Herzhafter Sauerteiglaib mit knuspriger Kruste, nahrhaft und mehrere Tage haltbar.',
    details: { producingHoldingName: 'Bäckerei', requiredProfession: 'Bäcker', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 7. BAUER & LANDWIRT (Farmer / Peasant)
  // =========================================================================
  {
    id: 'prof-farm-raw-seed-wheat',
    title: 'Weizensaat',
    builderType: 'Rohstoff',
    mainCategory: 'Landwirtschaft',
    subCategory: 'Saatgut & Saatgetreide',
    unit: 'Sack',
    pricePerUnit: 5,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Ausgelesenes, keimfähiges Saatgut für die Frühjahrs- oder Herbstbestellung der Felder.',
    details: { requiredProfession: 'Bauer', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-farm-tool-scythe',
    title: 'Sense',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Landwirtschaft & Erntewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 15,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Langes, geschwungenes Sensenblatt mit ergonomischem Holzstiel für die Getreide- und Heuernte.',
    details: { toolType: 'Sense', requiredProfession: 'Bauer', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-farm-tool-pitchfork',
    title: 'Heugabel',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Landwirtschaft & Erntewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 10,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dreizinkige Eisen- oder Eschenholz-Gabel zum Wenden und Verladen von Heu und Stroh.',
    details: { toolType: 'Heugabel', requiredProfession: 'Bauer', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-farm-tool-plow',
    title: 'Pflug',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Landwirtschaft & Erntewerkzeuge',
    unit: 'Stück',
    pricePerUnit: 60,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Schwerer Scharpflug mit eisernem Sech und Streichblech zum Umbrechen des Ackerbodens.',
    details: { toolType: 'Pflug', requiredProfession: 'Bauer', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-farm-cloth-strawhat',
    title: 'Strohhut',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Kopfbedeckungen & Hüte',
    unit: 'Stück',
    pricePerUnit: 3,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Breit geflochtener Weizenstrohhut als Sonnenschutz bei der harten Feldarbeit.',
    details: { clothingSlot: 'head', requiredProfession: 'Bauer', useDomains: ['alltag'] }
  },
  {
    id: 'prof-farm-cloth-shirt',
    title: 'Grobes Bauernhemd',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Alltagskleidung',
    unit: 'Stück',
    pricePerUnit: 6,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schlichtes, ungefärbtes Leinenhemd mit Holzknebeln am Halsausschnitt.',
    details: { clothingSlot: 'torso', requiredProfession: 'Bauer', useDomains: ['alltag'] }
  },

  // =========================================================================
  // 8. SCHNEIDER & WEBER (Tailor / Weaver)
  // =========================================================================
  {
    id: 'prof-tailor-raw-flax',
    title: 'Flachs',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Fasern & Textil-Rohstoffe',
    unit: 'kg',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Getrocknete Flachsstängel mit festen Bastfasern zur Gewinnung von reißfestem Leinengarn.',
    details: { baseRawMaterial: 'Flachs', requiredProfession: 'Weber', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-tailor-mat-linen',
    title: 'Leinenstoff',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Stoffe, Garne & Seile',
    unit: 'Ballen',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dicht gewebtes Tuch aus naturweißem Flachsgarn für Kleidung, Hemden und Säcke.',
    details: { fabricType: 'Leinen', requiredProfession: 'Schneider', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-tailor-mat-wool-cloth',
    title: 'Wollstoff',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Stoffe, Garne & Seile',
    unit: 'Ballen',
    pricePerUnit: 25,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Gewalkter, dichter Schafwollstoff für warme Mäntel, Decken und Hosen.',
    details: { fabricType: 'Wolle', requiredProfession: 'Schneider', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-tailor-tool-scissors',
    title: 'Schneiderschere',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Stück',
    pricePerUnit: 15,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schwere Eisenschere mit scharfen Schneidbacken für saubere Zuschnitte dicker Stoffe.',
    details: { toolType: 'Schere', requiredProfession: 'Schneider', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-tailor-tool-needles',
    title: 'Nähnadelset',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Set',
    pricePerUnit: 5,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Set feiner Stahlnadeln verschiedener Stärke samt Messing-Fingerhut.',
    details: { toolType: 'Nähnadeln', requiredProfession: 'Schneider', useDomains: ['handwerk', 'alltag'] }
  },
  {
    id: 'prof-tailor-tool-spinning-wheel',
    title: 'Spinnrad',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 45,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Präzise gefertigtes Holzspinnrad mit Fußtritt zum Verspinnen von Wolle und Flachs.',
    details: { toolType: 'Spinnrad', requiredProfession: 'Weber', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-tailor-cloth-vest',
    title: 'Schneiderweste',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Alltagskleidung',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Taillierte Wollweste mit Nadelkissen am Revers und Taschen für Maßbänder.',
    details: { clothingSlot: 'torso', requiredProfession: 'Schneider', useDomains: ['alltag'] }
  },
  {
    id: 'prof-tailor-prod-tunic',
    title: 'Leinentunika',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Alltagskleidung',
    unit: 'Stück',
    pricePerUnit: 12,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Bequeme Obertunika mit fein gesäumten Ärmeln und Gürtelschlaufen.',
    details: { producingHoldingName: 'Manufaktur', requiredProfession: 'Schneider', useDomains: ['alltag'] }
  },

  // =========================================================================
  // 9. GERBER & SCHUSTER (Tanner / Cobbler / Leatherworker)
  // =========================================================================
  {
    id: 'prof-tanner-raw-hide',
    title: 'Tierhaut',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Tierische Rohstoffe & Jagd',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Gesalzene, ungerarbte Rinder- oder Hirschhaut aus der Schlachtung.',
    details: { baseRawMaterial: 'Tierhaut', requiredProfession: 'Gerber', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-tanner-mat-leather',
    title: 'Leder',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Leder, Pergament & Felle',
    unit: 'Haut',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Pflanzlich mit Eichenlohe gegerbtes, geschmeidiges Glattleder.',
    details: { baseRawMaterial: 'Leder', requiredProfession: 'Gerber', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-tanner-mat-strips',
    title: 'Lederstreifen',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Leder, Pergament & Felle',
    unit: 'Bündel',
    pricePerUnit: 5,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Reißfeste Riemen aus Rindsleder für Rüstungsschnallungen und Handwerksbünde.',
    details: { requiredProfession: 'Gerber', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-tanner-tool-scraper',
    title: 'Schabmesser',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Zweigriffiges, gebogenes Klingenmesser zum Entfleischen und Enthaaren von Häuten am Gerbbock.',
    details: { toolType: 'Schabmesser', requiredProfession: 'Gerber', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-tanner-tool-awl',
    title: 'Stechahle',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Stück',
    pricePerUnit: 6,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Scharfe Dornahle aus Werkzeugstahl mit gedrechseltem Holzgriff zum Vorstechen von Nahtlöchern.',
    details: { toolType: 'Ahle', requiredProfession: 'Schuster', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-tanner-tool-last',
    title: 'Schusterleisten',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Paar',
    pricePerUnit: 16,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Hartholzform für Schuhe und Stiefel zum passgenauen Aufspannen und Nageln der Sohlen.',
    details: { toolType: 'Schusterleisten', requiredProfession: 'Schuster', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-tanner-cloth-boots',
    title: 'Wanderstiefel',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Schuhe, Stiefel & Schuhwerk',
    unit: 'Paar',
    pricePerUnit: 24,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Genagelte, robuste Schnürstiefel aus gefettetem Leder für unwegsames Gelände.',
    details: { clothingSlot: 'feet', producingHoldingName: 'Handwerkswerkstatt', requiredProfession: 'Schuster', useDomains: ['alltag', 'abenteuer'] }
  },

  // =========================================================================
  // 10. JÄGER & FALLENSTELLER (Hunter / Trapper)
  // =========================================================================
  {
    id: 'prof-hunt-weapon-bow',
    title: 'Jagdbogen',
    builderType: 'Waffe',
    mainCategory: 'Waffen',
    subCategory: 'Bögen & Pfeile',
    unit: 'Stück',
    pricePerUnit: 35,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Elastischer Flachbogen aus Eibenholz mit Sehne aus Tierdarm, präzise auf mittlere Distanz.',
    details: { weaponType: 'Bogen', requiredProfession: 'Jäger', useDomains: ['abenteuer', 'kampf', 'wirtschaft'] }
  },
  {
    id: 'prof-hunt-mat-arrows',
    title: 'Jagdpfeile',
    builderType: 'Material',
    mainCategory: 'Waffen',
    subCategory: 'Bögen & Pfeile',
    unit: 'Köcher',
    pricePerUnit: 8,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Zwanzig befiederte Eschenholzpfeile mit geschmiedeter Dreikantspitze.',
    details: { requiredProfession: 'Jäger', useDomains: ['abenteuer', 'kampf'] }
  },
  {
    id: 'prof-hunt-tool-knife',
    title: 'Ausweidmesser',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Jagd & Fallenbau',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Gebogene Aufbrechklinge aus rostträgem Kohlenstoffstahl zum sauberen Enthäuten von Wild.',
    details: { toolType: 'Jagdmesser', requiredProfession: 'Jäger', useDomains: ['handwerk', 'abenteuer'] }
  },
  {
    id: 'prof-hunt-tool-trap',
    title: 'Tellereisen',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Jagd & Fallenbau',
    unit: 'Stück',
    pricePerUnit: 22,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Kräftige Federfalle aus Schmiedeeisen zum Auslegen auf Wildwechseln.',
    details: { toolType: 'Falle', requiredProfession: 'Jäger', useDomains: ['wirtschaft', 'abenteuer'] }
  },
  {
    id: 'prof-hunt-cloth-cloak',
    title: 'Fellkragenmantel',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Mäntel, Umhänge & Wetterkleidung',
    unit: 'Stück',
    pricePerUnit: 35,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Wetterfester Wollmantel in Waldgrün mit warmem Wolfs- oder Fuchsfellkragen.',
    details: { clothingSlot: 'cloak', requiredProfession: 'Jäger', useDomains: ['alltag', 'abenteuer'] }
  },

  // =========================================================================
  // 11. FISCHER & SEEMANN (Fisher / Sailor)
  // =========================================================================
  {
    id: 'prof-fish-tool-net',
    title: 'Fischernetz',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Fischerei & Fanggerät',
    unit: 'Stück',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Geknüpftes Wurfnetz aus geölter Hanffaser mit Bleisinkern für See- und Flussfischerei.',
    details: { toolType: 'Fischernetz', requiredProfession: 'Fischer', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-fish-tool-rod',
    title: 'Angelrute',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Fischerei & Fanggerät',
    unit: 'Stück',
    pricePerUnit: 10,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Bambus- oder Haselnussrute mit gewachster Schnur, Korkpose und Bronsehaken.',
    details: { toolType: 'Angelrute', requiredProfession: 'Fischer', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-fish-cloth-southwester',
    title: 'Südwester',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Kopfbedeckungen & Hüte',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Geölter Regenhut mit verlängerter Nackenkrempe gegen Gischt und Starkregen.',
    details: { clothingSlot: 'head', requiredProfession: 'Fischer', useDomains: ['alltag'] }
  },
  {
    id: 'prof-fish-cloth-oilskin',
    title: 'Wachstuchmantel',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Mäntel, Umhänge & Wetterkleidung',
    unit: 'Stück',
    pricePerUnit: 25,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Mit Bienenwachs und Leinöl imprägnierter Mantel, absolut wind- und wasserdicht.',
    details: { clothingSlot: 'cloak', requiredProfession: 'Fischer', useDomains: ['alltag'] }
  },
  {
    id: 'prof-fish-prod-smoked-fish',
    title: 'Räucherfisch',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Fisch & Meeresfrüchte',
    unit: 'Stück',
    pricePerUnit: 3,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Über Buchenrauch golden geräucherter Lachs oder Forelle, haltbar und nahrhaft.',
    details: { producingHoldingName: 'Fischerei', requiredProfession: 'Fischer', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 12. ALCHEMIST & APOTHEKER (Alchemist / Herbalist)
  // =========================================================================
  {
    id: 'prof-alch-raw-herbs',
    title: 'Heilkräuter',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Kräuter & Alchemie',
    unit: 'Bund',
    pricePerUnit: 6,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Frisch gesammelte Schafgarbe, Spitzwegerich und Königskerze für Tinkturen und Wundsalben.',
    details: { baseRawMaterial: 'Kräuter', requiredProfession: 'Alchemist', useDomains: ['wirtschaft', 'medizin'] }
  },
  {
    id: 'prof-alch-mat-vial',
    title: 'Glasfläschchen',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Glas, Keramik & Ton',
    unit: 'Stück',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Sauber geblasenes Klarglasfläschchen mit dicht schließendem Naturkorken.',
    details: { requiredProfession: 'Alchemist', useDomains: ['wirtschaft', 'handwerk'] }
  },
  {
    id: 'prof-alch-tool-mortar',
    title: 'Mörser und Stößel',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Medizin- & Wundarztbesteck',
    unit: 'Set',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schwerer Granit- oder Messingmörser zum Zerreiben von Wurzeln, Harzen und Mineralien.',
    details: { toolType: 'Mörser', requiredProfession: 'Alchemist', useDomains: ['handwerk', 'medizin'] }
  },
  {
    id: 'prof-alch-tool-alembic',
    title: 'Alambik',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Medizin- & Wundarztbesteck',
    unit: 'Stück',
    pricePerUnit: 75,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Kupferner Destillierhelm mit Schwanenhals und Kühlkessel zur Gewinnung reinster Essenzen.',
    details: { toolType: 'Destillierkolben', requiredProfession: 'Alchemist', useDomains: ['handwerk', 'magie'] }
  },
  {
    id: 'prof-alch-cloth-robe',
    title: 'Alchemistengewand',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Berufsbekleidung',
    unit: 'Stück',
    pricePerUnit: 35,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dichte, säurebeständig imprägnierte Robe mit verstärkten Taschen für Phiolen und Zutaten.',
    details: { clothingSlot: 'body', requiredProfession: 'Alchemist', useDomains: ['handwerk', 'magie'] }
  },
  {
    id: 'prof-alch-prod-healing-potion',
    title: 'Heiltrank',
    builderType: 'Nahrung',
    mainCategory: 'Medizin',
    subCategory: 'Wundtränke & Elixiere',
    unit: 'Fläschchen',
    pricePerUnit: 25,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Rubinrot leuchtender Kräuterauszug, der Fleischwunden rasch schließt und Kraft spendet.',
    details: { producingHoldingName: 'Magierladen', requiredProfession: 'Alchemist', useDomains: ['abenteuer', 'medizin', 'kampf'] }
  },

  // =========================================================================
  // 13. BRAUER & WINZER (Brewer / Vintner)
  // =========================================================================
  {
    id: 'prof-brew-raw-hops',
    title: 'Hopfen',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Getreide & Feldfrüchte',
    unit: 'Sack',
    pricePerUnit: 4,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Aromatische Hopfendolden für die Würze und Haltbarmachung von Bier.',
    details: { requiredProfession: 'Brauer', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-brew-mat-barrel',
    title: 'Holzfass',
    builderType: 'Alltagsgegenstand',
    mainCategory: 'Alltags- & Haushaltsgegenstände',
    subCategory: 'Behälter, Truhen & Gefäße',
    unit: 'Stück',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dichtes Eichenfass mit geschmiedeten Eisenreifen für Bier, Wein oder Pökelfleisch.',
    details: { requiredProfession: 'Böttcher', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-brew-tool-mash-paddle',
    title: 'Maischekrücke',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Kochen & Küchenwerkzeuge',
    unit: 'Stück',
    pricePerUnit: 12,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Großes Rührpaddel aus Buchenholz mit Lochung zum Durchmischen des Sudkessels.',
    details: { toolType: 'Maischepaddel', requiredProfession: 'Brauer', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-brew-cloth-apron',
    title: 'Brauerschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 14,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Wasserfeste, dicke Leinenschürze mit Ledereinsätzen gegen heiße Würzspritzer.',
    details: { clothingSlot: 'body', requiredProfession: 'Brauer', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-brew-prod-beer',
    title: 'Helles Bier',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Getränke, Bier & Wein',
    unit: 'Krug',
    pricePerUnit: 1,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Süffiges, bernsteinfarbenes Gerstenbier mit weißer Schaumkrone.',
    details: { producingHoldingName: 'Taverne', requiredProfession: 'Brauer', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 14. KOCH & WIRT (Cook / Chef / Innkeeper)
  // =========================================================================
  {
    id: 'prof-cook-tool-knife',
    title: 'Kochmesser',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Kochen & Küchenwerkzeuge',
    unit: 'Stück',
    pricePerUnit: 16,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Breites, rasiermesserscharf geschliffenes Küchenmesser zum Schneiden von Fleisch und Gemüse.',
    details: { toolType: 'Kochmesser', requiredProfession: 'Koch', useDomains: ['handwerk', 'alltag'] }
  },
  {
    id: 'prof-cook-tool-pan',
    title: 'Gusseisenpfanne',
    builderType: 'Alltagsgegenstand',
    mainCategory: 'Alltags- & Haushaltsgegenstände',
    subCategory: 'Geschirr & Kochgeschirr',
    unit: 'Stück',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schwere Pfanne aus Gusseisen für offenes Herdfeuer mit ausgezeichneter Wärmehaltung.',
    details: { toolType: 'Bratpfanne', requiredProfession: 'Koch', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-cook-cloth-hat',
    title: 'Kochhaube',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Kopfbedeckungen & Hüte',
    unit: 'Stück',
    pricePerUnit: 5,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Gefältelte weiße Leinenmütze für Küchenmeister.',
    details: { clothingSlot: 'head', requiredProfession: 'Koch', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-cook-cloth-apron',
    title: 'Kochschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Weiße, kochfeste Schürze zum Schutz vor Fettspritzern und Bratensaft.',
    details: { clothingSlot: 'body', requiredProfession: 'Koch', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-cook-prod-stew',
    title: 'Fleischeintopf',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Frischwaren & Grundnahrungsmittel',
    unit: 'Schüssel',
    pricePerUnit: 3,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Dampfender Eintopf mit Rindfleisch, Wurzelgemüse, Zwiebeln und Kräutern.',
    details: { producingHoldingName: 'Gasthaus', requiredProfession: 'Koch', useDomains: ['alltag'] }
  },

  // =========================================================================
  // 15. HEILER, FELDSCHER & WUNDARZT (Healer / Surgeon)
  // =========================================================================
  {
    id: 'prof-heal-mat-bandages',
    title: 'Leinenverband',
    builderType: 'Material',
    mainCategory: 'Medizin',
    subCategory: 'Verbandszeug & Erste Hilfe',
    unit: 'Rolle',
    pricePerUnit: 3,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Ausgekochtes, steriles Leinenband zum Verbinden von Schnitt- und Bisswunden.',
    details: { requiredProfession: 'Heiler', useDomains: ['medizin', 'abenteuer'] }
  },
  {
    id: 'prof-heal-tool-scalpel',
    title: 'Skalpellset',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Medizin- & Wundarztbesteck',
    unit: 'Set',
    pricePerUnit: 30,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Fein geschliffene Chirurgenklingen im Holzkästchen für Notoperationen und Wundversorgung.',
    details: { toolType: 'Skalpell', requiredProfession: 'Heiler', useDomains: ['medizin', 'handwerk'] }
  },
  {
    id: 'prof-heal-cloth-coat',
    title: 'Arztkittel',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Berufsbekleidung',
    unit: 'Stück',
    pricePerUnit: 20,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Hell gebleichter, waschbarer Leinenkittel für Heiler und Feldscherer.',
    details: { clothingSlot: 'body', requiredProfession: 'Heiler', useDomains: ['medizin'] }
  },

  // =========================================================================
  // 16. SCHREIBER & KARTOGRAF (Scribe / Cartographer)
  // =========================================================================
  {
    id: 'prof-scribe-mat-parchment',
    title: 'Pergament',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Papier, Tinte & Schreibstoffe',
    unit: 'Bogen',
    pricePerUnit: 6,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Glatt geschabte Ziegen- oder Kalbshaut für langlebige Verträge, Urkunden und Karten.',
    details: { requiredProfession: 'Schreiber', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-scribe-mat-ink',
    title: 'Tinte',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Papier, Tinte & Schreibstoffe',
    unit: 'Fläschchen',
    pricePerUnit: 8,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Tiefschwarze Eisengallustinte, lichtecht und dokumentenecht.',
    details: { requiredProfession: 'Schreiber', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-scribe-tool-quill',
    title: 'Schreibfeder',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Stück',
    pricePerUnit: 2,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Präzise zugeschnittener Gänsekiel für feine Schriftzüge und Urkunden.',
    details: { toolType: 'Schreibfeder', requiredProfession: 'Schreiber', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-scribe-cloth-robe',
    title: 'Schreibergewand',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Berufsbekleidung',
    unit: 'Stück',
    pricePerUnit: 22,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dunkle Wollrobe mit schwarzen Ärmelschonern zum Schutz vor Tintenflecken.',
    details: { clothingSlot: 'body', requiredProfession: 'Schreiber', useDomains: ['alltag'] }
  },
  {
    id: 'prof-scribe-prod-map',
    title: 'Landkarte',
    builderType: 'Alltagsgegenstand',
    mainCategory: 'Alltags- & Haushaltsgegenstände',
    subCategory: 'Schreib- & Dokumentenbedarf',
    unit: 'Rolle',
    pricePerUnit: 40,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Detaillierte Pergamentkarte der Region mit Handelsstraßen, Flüssen und Siedlungen.',
    details: { producingHoldingName: 'Handwerkswerkstatt', requiredProfession: 'Kartograf', useDomains: ['abenteuer', 'wirtschaft'] }
  },

  // =========================================================================
  // 17. GOLDSCHMIED & JUWELIER (Goldsmith / Jeweler)
  // =========================================================================
  {
    id: 'prof-gold-raw-gold',
    title: 'Golderz',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Edelmetalle & Edelsteine',
    unit: 'g',
    pricePerUnit: 25,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Selten / Kostbar',
    isUnique: false,
    condition: 'makellos',
    description: 'Reine Goldkörner und Quarzadern aus tiefen Berggängen.',
    details: { baseRawMaterial: 'Gold', requiredProfession: 'Goldschmied', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-gold-mat-gold-ingot',
    title: 'Goldbarren',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Barren & Metallhalbzeuge',
    unit: 'Stück',
    pricePerUnit: 250,
    materialQuality: 'Perfekt / Makellos',
    rarity: 'Selten / Kostbar',
    isUnique: false,
    condition: 'makellos',
    description: 'Gegossener Feingoldbarren mit amtlicher Punze für Münzprägung und Juwelierkunst.',
    details: { baseRawMaterial: 'Gold', requiredProfession: 'Goldschmied', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-gold-tool-loupe',
    title: 'Lupenglas',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Stück',
    pricePerUnit: 35,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Präzisionsgeschliffene Lupe mit Messingfassung für feine Gravuren und Edelsteinfassungen.',
    details: { toolType: 'Lupe', requiredProfession: 'Goldschmied', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-gold-prod-ring',
    title: 'Goldring',
    builderType: 'Handelsware',
    mainCategory: 'Handelswaren',
    subCategory: 'Luxusgüter & Schmuck',
    unit: 'Stück',
    pricePerUnit: 60,
    materialQuality: 'Perfekt / Makellos',
    rarity: 'Selten / Kostbar',
    isUnique: false,
    condition: 'makellos',
    description: 'Poliertes Schmuckstück aus massivem Feingold mit filigranen Ornamentgravuren.',
    details: { producingHoldingName: 'Handwerkswerkstatt', requiredProfession: 'Goldschmied', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 18. WACHSOLDAT & SÖLDNER (Guard / Soldier)
  // =========================================================================
  {
    id: 'prof-guard-weapon-halberd',
    title: 'Hellebarde',
    builderType: 'Waffe',
    mainCategory: 'Waffen',
    subCategory: 'Stangenwaffen & Speere',
    unit: 'Stück',
    pricePerUnit: 45,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Zweieinhalb Meter lange Stangenwaffe mit Beilblatt, Stoßspitze und Haken zur Kavallerieabwehr.',
    details: { weaponType: 'Stangenwaffe', requiredProfession: 'Wachsoldat', useDomains: ['armee', 'kampf'] }
  },
  {
    id: 'prof-guard-armor-chainmail',
    title: 'Kettenhemd',
    builderType: 'Rüstung',
    mainCategory: 'Rüstung & Schutzausrüstung',
    subCategory: 'Mittlere Rüstung (Kette, Schuppenpanzer)',
    unit: 'Stück',
    pricePerUnit: 90,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Geflecht aus vernieteten Stahlringen, bietet hervorragenden Schutz vor Hieb- und Schnittwaffen.',
    details: { clothingSlot: 'torso', requiredProfession: 'Wachsoldat', useDomains: ['armee', 'kampf'] }
  },
  {
    id: 'prof-guard-cloth-tabard',
    title: 'Wappenrock',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Militäruniformen & Truppenkleidung',
    unit: 'Stück',
    pricePerUnit: 18,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Ärmelloser Überwurf in den Farben und mit dem Wappen der Stadtgarde.',
    details: { clothingSlot: 'cloak', requiredProfession: 'Wachsoldat', useDomains: ['armee'] }
  },

  // =========================================================================
  // 19. KAUFMANN & HÄNDLER (Merchant)
  // =========================================================================
  {
    id: 'prof-merch-tool-scale',
    title: 'Kaufmannswaage',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Schreib- & Feinmechanikerwerkzeug',
    unit: 'Set',
    pricePerUnit: 28,
    materialQuality: 'Meisterhaft / Veredelt',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Balancierte Messing-Balkenwaage mit geeichten Gewichten zur Prüfung von Münzen und Gewürzen.',
    details: { toolType: 'Waage', requiredProfession: 'Kaufmann', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-merch-cloth-doublet',
    title: 'Samtwams',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Festkleidung & Trachten',
    unit: 'Stück',
    pricePerUnit: 50,
    materialQuality: 'Perfekt / Makellos',
    rarity: 'Selten / Kostbar',
    isUnique: false,
    condition: 'neu',
    description: 'Edles Obergewand aus dunkelblauem Samt mit Seidenfutter und Silberknöpfen.',
    details: { clothingSlot: 'torso', requiredProfession: 'Kaufmann', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 20. TÖPFER (Potter)
  // =========================================================================
  {
    id: 'prof-pot-raw-clay',
    title: 'Rohton',
    builderType: 'Rohstoff',
    mainCategory: 'Rohstoffe',
    subCategory: 'Steine, Erden & Ton',
    unit: 'kg',
    pricePerUnit: 1,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Plastischer, feuchter Grubenlehm zur Aufbereitung für Drehscheibe und Brennofen.',
    details: { baseRawMaterial: 'Ton', requiredProfession: 'Töpfer', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-pot-tool-wheel',
    title: 'Töpferscheibe',
    builderType: 'Werkzeug',
    mainCategory: 'Werkzeuge',
    subCategory: 'Holzbearbeitung & Schreinerei',
    unit: 'Stück',
    pricePerUnit: 40,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'neu',
    description: 'Schwere, fußgetriebene Schwungradscheibe zum Formen rotationssymmetrischer Tongefäße.',
    details: { toolType: 'Töpferscheibe', requiredProfession: 'Töpfer', useDomains: ['handwerk', 'wirtschaft'] }
  },
  {
    id: 'prof-pot-cloth-apron',
    title: 'Töpferschürze',
    builderType: 'Kleidung',
    mainCategory: 'Kleidung & Textilien',
    subCategory: 'Arbeits- & Schutzkleidung',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Schürze aus schwerem Leinentuch zum Schutz vor Tonschlicker und Wasserspritzern.',
    details: { clothingSlot: 'body', requiredProfession: 'Töpfer', useDomains: ['handwerk'] }
  },
  {
    id: 'prof-pot-prod-pitcher',
    title: 'Tonkrug',
    builderType: 'Alltagsgegenstand',
    mainCategory: 'Alltags- & Haushaltsgegenstände',
    subCategory: 'Geschirr & Kochgeschirr',
    unit: 'Stück',
    pricePerUnit: 3,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Gebrannter, innen glasierter Krug mit Henkel für Wasser, Milch oder Schankbier.',
    details: { producingHoldingName: 'Handwerkswerkstatt', requiredProfession: 'Töpfer', useDomains: ['alltag'] }
  },

  // =========================================================================
  // 21. BÄCKEREI & MÜHLE (Bakery & Mill - Food Production)
  // =========================================================================
  {
    id: 'prof-food-rye-bread',
    title: 'Sauerteig-Roggenbrot',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Brot, Gebäck & Getreideprodukte',
    unit: 'Laib',
    pricePerUnit: 2,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Herzhaftes, dunkles Sauerteigbrot mit dicker Kruste aus dem Holzbackofen. Nahrhaft und tageundlang haltbar.',
    details: { producingHoldingName: 'Bäckerei', requiredProfession: 'Bäcker', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-wheat-bread',
    title: 'Weizen-Weißbrot',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Brot, Gebäck & Getreideprodukte',
    unit: 'Laib',
    pricePerUnit: 2,
    materialQuality: 'Fein / Gebleicht',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Luftiges, helles Weizenbrot mit feiner Porung. Beliebt bei städtischen Bürgerfamilien und Festtafeln.',
    details: { producingHoldingName: 'Bäckerei', requiredProfession: 'Bäcker', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-pretzel',
    title: 'Laugenbrezel',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Brot, Gebäck & Getreideprodukte',
    unit: 'Stück',
    pricePerUnit: 1,
    materialQuality: 'Gewöhnlich / Standard',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Kross gebackenes Salzgebäck mit Kastanienbrauner Laugenkruste, ideal zu Bierschank und Käse.',
    details: { producingHoldingName: 'Bäckerei', requiredProfession: 'Bäcker', useDomains: ['alltag'] }
  },
  {
    id: 'prof-food-pastry-apple',
    title: 'Frucht-Hefegebäck',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Brot, Gebäck & Getreideprodukte',
    unit: 'Stück',
    pricePerUnit: 3,
    materialQuality: 'Süß / Fein',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'frisch',
    description: 'Feiner Hefeteig gefüllt mit gedünsteten Zimtäpfeln, Rosinen und Mandelblättchen.',
    details: { producingHoldingName: 'Bäckerei', requiredProfession: 'Bäcker', useDomains: ['alltag'] }
  },
  {
    id: 'prof-food-biscuit',
    title: 'Schiffszwieback',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Haltbare Rationen & Reiseverpflegung',
    unit: 'Beutel',
    pricePerUnit: 3,
    materialQuality: 'Hart / Trocken',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Doppelt gebackene, knochentrockene Brotwürfel. Extrem lange haltbar für Seereisen, Festungsbesatzungen und Abenteuer.',
    details: { producingHoldingName: 'Bäckerei', requiredProfession: 'Bäcker', useDomains: ['abenteuer', 'armee'] }
  },
  {
    id: 'prof-food-wheat-flour',
    title: 'Feines Weizenmehl',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Nahrungsmittel-Zwischenprodukte',
    unit: 'Sack',
    pricePerUnit: 4,
    materialQuality: 'Fein / Siebt',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Mehrfach gesiebtes Weizenmehl aus den Granitmahlsteinen der Wassermühle. Grundstoff für Bäckereien.',
    details: { producingHoldingName: 'Mühle', requiredProfession: 'Müller', useDomains: ['wirtschaft'] }
  },
  {
    id: 'prof-food-rye-meal',
    title: 'Roggen-Vollkornmehl',
    builderType: 'Material',
    mainCategory: 'Materialien & Zwischenprodukte',
    subCategory: 'Nahrungsmittel-Zwischenprodukte',
    unit: 'Sack',
    pricePerUnit: 3,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Dunkles, schrotiges Roggenmehl voller Keimstoffe für herzhafte Brotteige.',
    details: { producingHoldingName: 'Mühle', requiredProfession: 'Müller', useDomains: ['wirtschaft'] }
  },

  // =========================================================================
  // 22. METZGEREI & FLEISCHEREI (Butcher Shop - Meat Production)
  // =========================================================================
  {
    id: 'prof-food-beef-roast',
    title: 'Rinderbraten-Lende',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Fleischwaren & Geflügel',
    unit: 'kg',
    pricePerUnit: 6,
    materialQuality: 'Zart / Abgehangen',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Gut marmoriertes, abgehangenes Rindfleisch aus der lokalen Weidehaltung für Braten und Schmorgerichte.',
    details: { producingHoldingName: 'Metzgerei', requiredProfession: 'Metzger', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-smoked-ham',
    title: 'Buchenholz-Räucherschinken',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Fleischwaren & Geflügel',
    unit: 'Stück',
    pricePerUnit: 12,
    materialQuality: 'Meisterhaft / Würzig',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'gut',
    description: 'Über Buchenspänen und Wacholderbeeren geräucherte Schinkenkeule. Über Monate haltbar.',
    details: { producingHoldingName: 'Metzgerei', requiredProfession: 'Metzger', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-sausage-ring',
    title: 'Würzige Knoblauch-Bauernwurst',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Fleischwaren & Geflügel',
    unit: 'Ring',
    pricePerUnit: 4,
    materialQuality: 'Solide / Gehoben',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'gut',
    description: 'Luftgetrocknete Rohwurst mit Pfefferkörnern und Knoblauch im Naturdarm.',
    details: { producingHoldingName: 'Metzgerei', requiredProfession: 'Metzger', useDomains: ['alltag', 'abenteuer'] }
  },
  {
    id: 'prof-food-pork-belly',
    title: 'Pökelfleisch-Schweinebauch',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Haltbare Rationen & Reiseverpflegung',
    unit: 'kg',
    pricePerUnit: 5,
    materialQuality: 'Gesalzen / Haltbar',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'gut',
    description: 'In Salzlake eingelegtes Fettfleisch für Schiffsproviant und winterliche Schmortöpfe.',
    details: { producingHoldingName: 'Metzgerei', requiredProfession: 'Metzger', useDomains: ['wirtschaft', 'armee'] }
  },
  {
    id: 'prof-food-lard',
    title: 'Grieben-Schmalztopf',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Molkereiprodukte, Öle & Fette',
    unit: 'Tontopf',
    pricePerUnit: 3,
    materialQuality: 'Herzhaft / Rein',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'gut',
    description: 'Ausgelassenes Schweinefett mit knusprigen Speckgrieben und Majoran im versiegelten Tontopf.',
    details: { producingHoldingName: 'Metzgerei', requiredProfession: 'Metzger', useDomains: ['alltag'] }
  },

  // =========================================================================
  // 23. KÄSEREI & SENNERHÜTTE (Dairy & Cheese House)
  // =========================================================================
  {
    id: 'prof-food-aged-cheese',
    title: 'Reifer Bergkäse-Laib',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Molkereiprodukte, Öle & Fette',
    unit: 'Laib',
    pricePerUnit: 15,
    materialQuality: 'Würzig / Reif',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'gut',
    description: 'Acht Monate im kühlen Felsenkeller gepflegter Hartkäse aus Rohmilch mit Naturrinde.',
    details: { producingHoldingName: 'Käserei', requiredProfession: 'Käser', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-goat-cheese',
    title: 'Kräuter-Ziegenkäserolle',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Molkereiprodukte, Öle & Fette',
    unit: 'Stück',
    pricePerUnit: 5,
    materialQuality: 'Aromatisch / Frisch',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Weicher Ziegenkäse umhüllt von Rosmarin, Thymian und schwarzem Pfeffer.',
    details: { producingHoldingName: 'Käserei', requiredProfession: 'Käser', useDomains: ['alltag'] }
  },
  {
    id: 'prof-food-butter-pot',
    title: 'Frische Alpen-Fassbutter',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Molkereiprodukte, Öle & Fette',
    unit: 'Tontopf',
    pricePerUnit: 4,
    materialQuality: 'Rahmig / Gesalzen',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Gestoßene Rahmbutter mit feiner Meersalznote im Steinguttopf.',
    details: { producingHoldingName: 'Käserei', requiredProfession: 'Käser', useDomains: ['alltag', 'wirtschaft'] }
  },

  // =========================================================================
  // 24. FISCHEREI & RÄUCHEREI (Fishery & Smokehouse)
  // =========================================================================
  {
    id: 'prof-food-smoked-salmon',
    title: 'Erlenholz-Räucherlachs',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Fisch & Meeresfrüchte',
    unit: 'Stück',
    pricePerUnit: 8,
    materialQuality: 'Edel / Zart',
    rarity: 'Ungewöhnlich / Regional',
    isUnique: false,
    condition: 'gut',
    description: 'Kalt geräuchertes Lachsfilet aus klaren Gebirgsflüssen mit feiner Rauchnote.',
    details: { producingHoldingName: 'Fischerei', requiredProfession: 'Fischer', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-salted-herring',
    title: 'Pökelhering im Holzfass',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Haltbare Rationen & Reiseverpflegung',
    unit: 'Fass',
    pricePerUnit: 25,
    materialQuality: 'Gesalzen / Haltbar',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'gut',
    description: 'Dicht in Starklake geschichtete Seeringe für Vorratskammern und lange Seereisen.',
    details: { producingHoldingName: 'Fischerei', requiredProfession: 'Fischer', useDomains: ['wirtschaft', 'armee'] }
  },

  // =========================================================================
  // 25. IMKEREI, OBSTBAU & GASTWIRTSCHAFT (Bee Farm, Orchard & Tavern)
  // =========================================================================
  {
    id: 'prof-food-honey-jar',
    title: 'Blüten-Bienenhonig',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Konserven, Süßwaren & Spezialitäten',
    unit: 'Tontopf',
    pricePerUnit: 6,
    materialQuality: 'Rein / Goldgelb',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'gut',
    description: 'Naturbelassener Bienenhonig aus Wiesenblütentrachten. Süßungsmittel und Hausmittel gegen Halsschmerzen.',
    details: { producingHoldingName: 'Imkerei', requiredProfession: 'Imker', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-apple-crate',
    title: 'Kiste Königsäpfel',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Obst, Gemüse & Feldfrüchte',
    unit: 'Kiste',
    pricePerUnit: 8,
    materialQuality: 'Knackig / Saftig',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Sorgfältig gepflückte, saftige Rotäpfel aus den regionalen Streuobstwiesen.',
    details: { producingHoldingName: 'Obstgut', requiredProfession: 'Obstbauer', useDomains: ['wirtschaft', 'alltag'] }
  },
  {
    id: 'prof-food-sauerkraut-barrel',
    title: 'Fass Sauerkraut',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Obst, Gemüse & Feldfrüchte',
    unit: 'Fass',
    pricePerUnit: 15,
    materialQuality: 'Vergoren / Würzig',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'gut',
    description: 'Milchsauer eingestampfter Weißkohl mit Wacholder und Kümmel. Schützt vor Mangelkrankheiten im Winter.',
    details: { producingHoldingName: 'Bauernhof', requiredProfession: 'Bauer', useDomains: ['alltag', 'wirtschaft'] }
  },
  {
    id: 'prof-food-roast-pork',
    title: 'Spanferkelbraten mit Kruste',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Frischwaren & Grundnahrungsmittel',
    unit: 'Teller',
    pricePerUnit: 5,
    materialQuality: 'Herzhaft / Knusprig',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Saftiges Spanferkelfleisch am Spieß geröstet mit krosser Schwarte, Biersauce und Semmelknödel.',
    details: { producingHoldingName: 'Gasthaus', requiredProfession: 'Koch', useDomains: ['alltag'] }
  },
  {
    id: 'prof-food-rabbit-stew',
    title: 'Wildhasen-Pfeffertopf',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Frischwaren & Grundnahrungsmittel',
    unit: 'Schüssel',
    pricePerUnit: 4,
    materialQuality: 'Würzig / Zart',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'frisch',
    description: 'Langsam geschmorter Hasenpfeffer mit Rotwein, Preiselbeeren und Waldpilzen.',
    details: { producingHoldingName: 'Gasthaus', requiredProfession: 'Koch', useDomains: ['alltag'] }
  },
  {
    id: 'prof-food-travel-ration',
    title: 'Marschration für Abenteurer',
    builderType: 'Nahrung',
    mainCategory: 'Nahrung',
    subCategory: 'Haltbare Rationen & Reiseverpflegung',
    unit: 'Paket',
    pricePerUnit: 8,
    materialQuality: 'Nahrhaft / Kompakt',
    rarity: 'Gewöhnlich / Alltäglich',
    isUnique: false,
    condition: 'neu',
    description: 'Wachstuchbeutel gepackt für 3 Tage Expedition: Dörrfleisch, Hartkäse, Nüsse, Trockenobst und Schiffszwieback.',
    details: { producingHoldingName: 'Taverne', requiredProfession: 'Koch', useDomains: ['abenteuer', 'armee'] }
  }
];
